# Generated by Django 3.1.1 on 2020-09-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjoinresquest',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='accept this request'),
        ),
    ]
