# Generated by Django 3.1.1 on 2020-10-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201005_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archive this event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name=' accept this event'),
        ),
    ]
