# Generated by Django 3.1.1 on 2020-10-08 15:32

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201006_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjoinresquest',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_pics', validators=[api.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='profile pic'),
        ),
        migrations.AlterField(
            model_name='userjoinresquest',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='event description'),
        ),
    ]
