# Generated by Django 3.1.1 on 2020-10-13 13:25

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201008_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='key',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventpictures',
            name='pictures',
            field=models.ImageField(upload_to='users/event_pictures/None', validators=[api.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='profile pic'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
