# Generated by Django 3.1.1 on 2020-10-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201024_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEndConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='event text')),
                ('accepted', models.BooleanField(null=True, verbose_name='event confirmation accepted')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event', verbose_name='event confirmed')),
            ],
        ),
    ]
