# Generated by Django 3.1.1 on 2020-10-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='api.Tags', verbose_name='event tags'),
        ),
        migrations.AddField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(to='api.Tags', verbose_name='event tags'),
        ),
    ]
