# Generated by Django 3.1.1 on 2020-11-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201031_0748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
